apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: {{ .Values.tekton.pipeline.name }}
  labels:
    {{- include "canopy-tekton-pipeline.labels" . | nindent 4 }}
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: GIT_URL
      type: string
      default: {{ .Values.git.url | quote }}
      description: Git repository URL
    - name: GIT_REVISION
      type: string
      default: {{ .Values.git.revision | quote }}
      description: Git revision to clone
    - name: BASE_URL
      type: string
      default: {{ .Values.kfp.baseUrl | quote }}
      description: Base URL for LlamaStack
    - name: BACKEND_URL
      type: string
      default: {{ .Values.kfp.backendUrl | quote }}
      description: Backend URL for canopy
  tasks:
    - name: git-clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: URL
          value: "$(params.GIT_URL)"
        - name: REVISION
          value: "$(params.GIT_REVISION)"
        - name: DELETE_EXISTING
          value: "true"
        - name: SSL_VERIFY
          value: "true"
    - name: execute-kfp-pipeline
      taskRef:
        name: {{ .Values.tekton.task.name }}
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: BASE_URL
          value: "$(params.BASE_URL)"
        - name: BACKEND_URL
          value: "$(params.BACKEND_URL)"
        - name: GIT_SHORT_REVISION
          value: ""
      runAfter:
        - git-clone