apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: canopy-test-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: GIT_URL
      type: string
      default: https://github.com/rhoai-genaiops/canopy-evals
      description: Git repository URL
    - name: GIT_BRANCH
      type: string
      default: "main"
      description: Git branch to clone
    - name: GIT_REVISION
      type: string
      default: "latest"
      description: Git revision to clone
    - name: GIT_SHORT_REVISION
      type: string
      default: "latest"
      description: Short Git commit hash
    - name: BASE_URL
      type: string
      default: {{ .Values.kfp.baseUrl | quote }}
      description: Base URL for LlamaStack
    - name: BACKEND_URL
      type: string
      default: {{ .Values.kfp.backendUrl | quote }}
      description: Backend URL for canopy
  tasks:
    - name: git-clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines 
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: URL
          value: "$(params.GIT_URL)"
        - name: REVISION
          value: "main"
        - name: DELETE_EXISTING
          value: "true"
        - name: SSL_VERIFY
          value: "false"
    - name: kfp-evaluation-task
      taskRef:
        name: kfp-evaluation-task
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: BASE_URL
          value: "$(params.BASE_URL)"
        - name: BACKEND_URL
          value: "$(params.BACKEND_URL)"
        - name: GIT_URL
          value: "$(params.GIT_URL)"
        - name: GIT_BRANCH
          value: "$(params.GIT_BRANCH)"
        - name: GIT_REVISION
          value: "$(params.GIT_REVISION)"
        - name: GIT_SHORT_REVISION
          value: "$(params.GIT_SHORT_REVISION)"
      runAfter:
        - git-clone