apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  labels:
    {{- include "canopy-tekton-pipeline.labels" . | nindent 4 }}
  annotations:
    {{- include "canopy-tekton-pipeline.annotations" . | nindent 4 }}
    openshift.io/description: 'Pipeline PVC for Canopy testing'
    openshift.io/display-name: 'Canopy Pipeline PVC'
spec:
  accessModes:
    {{- toYaml .Values.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ .Values.pvc.storageClass }}
  volumeMode: Filesystem