---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: canopy-test-trigger-template
  labels:
    {{- include "canopy-tekton-pipeline.labels" . | nindent 4 }}
  annotations:
    {{- include "canopy-tekton-pipeline.annotations" . | nindent 4 }}
spec:
  params:
    - name: gitrepositoryurl
      description: The git repository url
    - name: git-revision
      description: The git revision
      default: {{ .Values.git.backendRevision }}
    - name: git-short-revision
      description: Seven character git sha
    - name: git-ref
      description: The full git ref
      default: refs/heads/main
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: canopy-test-pipeline-
        labels:
          {{- include "canopy-tekton-pipeline.labels" . | nindent 10 }}
      spec:
        pipelineRef:
          name: canopy-test-pipeline
        params:
          - name: GIT_URL
            value: $(tt.params.gitrepositoryurl)
          - name: GIT_REVISION
            value: $(tt.params.git-revision)
          - name: GIT_SHORT_REVISION
            value: $(tt.params.git-short-revision)
          - name: BASE_URL
            value: {{ .Values.kfp.baseUrl | quote }}
          - name: BACKEND_URL
            value: {{ .Values.kfp.backendUrl | quote }}
        workspaces:
        - name: shared-workspace
          persistentVolumeClaim:
            claimName: shared-workspace

---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: canopy-test-git-trigger
  labels:
    {{- include "canopy-tekton-pipeline.labels" . | nindent 4 }}
  annotations:
    {{- include "canopy-tekton-pipeline.annotations" . | nindent 4 }}
spec:
  interceptors:
    - ref:
        name: "cel"
      params:
        - name: filter
          value: (body.ref == 'refs/heads/main')
        - name: overlays
          value:
          - expression: body.head_commit.id.truncate(7)
            key: truncated_sha
  bindings:
    - name: git-revision
      value: $(body.head_commit.id)
    - name: git-short-revision
      value: $(extensions.truncated_sha)
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
    - name: git-ref
      value: $(body.ref)
  template:
    ref: canopy-test-trigger-template

---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: canopy-test-event-listener
  labels:
    {{- include "canopy-tekton-pipeline.labels" . | nindent 4 }}
  annotations:
    {{- include "canopy-tekton-pipeline.annotations" . | nindent 4 }}
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: canopy-test-git-trigger