apiVersion: v2
name: canopy-tekton-pipeline
description: A Helm chart for Canopy Test Pipeline using Tekton and Kubeflow
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - tekton
  - kubeflow
  - testing
  - llm
  - canopy
home: https://github.com/rhoai-genaiops/canopy-prompts
maintainers:
  - name: GenAI Team
    email: genai@redhat.com