USER_NAME: "your-username"
kfp:
  baseUrl: "http://llama-stack"
  backendUrl: "http://canopy-backend"
secrets:
  s3:
    name: "test-results"
git:
  eval_url: https://github.com/rhoai-genaiops/canopy-evals