prompts:
  - "Summarize the following text in a concise manner: {{text}}"
  # - file://prompts.txt
providers:
  - id: https
    config:
      url: 'http://llama32-predictor.genaiops-playground.svc.cluster.local:8080/v1/completions'
      method: 'POST'
      headers:
        'Content-Type': 'application/json'
      body:
        prompt: '{{prompt}}'
      transformResponse: 'json.choices[0].text'
defaultTest:
  assert:
    - type: javascript
      value: Math.max(0, Math.min(1, 1 - (output.length - 100) / 900));
    - type: latency
      threshold: 2000
tests:
  - vars:
      text: "Llama 3.2 is a state-of-the-art language model that excels in various natural language processing tasks, including summarization, translation, and question answering."
  - vars:
      text: "The Llama 3.2 model has shown remarkable performance in generating coherent and contextually relevant summaries across diverse datasets, making it a valuable tool for summarization tasks."