USER_NAME: "your-username"
kfp:
  llsUrl: "http://llama-stack"
  backendUrl: "http://canopy-backend"
  endpointPath: "/summarize"
secrets:
  s3:
    name: "test-results"
git:
  eval_url: https://github.com/rhoai-genaiops/canopy-evals